// src/components/type-selector.tsx
import React, { ChangeEvent, useState } from "react";
import { TYPEATK, TYPEDEF, TYPES } from "../components/poke-type";
import "../styles/type-selector.css";
import { type } from "os";

function TypeSelector({isDEFPage} : {isDEFPage: string}) {

  const typeList = TYPES.map(type => <option>{type}</option> );
  let DEFcontent;

  const getInitialState = () => {
    return "none";
  };

  const handleTypeOneChange = (typeOne: ChangeEvent<HTMLSelectElement>) => {
    setTypeOne(typeOne.target.value);
  };

  const handleTypeTwoChange = (typeTwo: ChangeEvent<HTMLSelectElement>) => {
    setTypeTwo(typeTwo.target.value);
  };

  const [typeOne, setTypeOne] = useState(getInitialState);
  const [typeTwo, setTypeTwo] = useState(getInitialState);

  if(isDEFPage === "true") {
    DEFcontent = (
      <div className="typeTwoContainer">
      <label>Type 2: </label>
      <div className="select-wrapper">
        <select id="typeTwoSelect" title="Select a type" value={typeTwo} onChange={(typeTwo) => handleTypeTwoChange(typeTwo)}>
            <option>none</option>
            {typeList}
        </select>
      </div>
      <p>T2: {typeTwo} </p>
    </div>
    )
}
  
  return(
    <React.Fragment>
      <div className ="center">
        <div className="typeOneContainer">
          <label>Type 1: </label>
          <div className="select-wrapper">
            <select id="typeOneSelect" title="Select a type" value={typeOne} onChange={(typeOne) => handleTypeOneChange(typeOne)}>
                <option>none</option>
                {typeList}
            </select>
        </div>
        <p>T1: {typeOne} </p>
      </div>

        {DEFcontent}
      </div>
    </React.Fragment>
  );
}

export default TypeSelector;

// src/app/type-selector/type-selector.component.ts
import { Component, OnInit, Output, Input, EventEmitter } from '@angular/core';
import { TYPEATK, TYPEDEF, TYPES } from 'src/poke-type';
import { TypeBadgeComponent } from '../type-badge/type-badge.component';

@Component({
  selector: 'app-type-selector',
  templateUrl: './type-selector.component.html',
  styleUrls: ['./type-selector.component.css']
})

export class TypeSelectorComponent {
  typeList = TYPES;
  @Output() newTypeOneEvent = new EventEmitter<string>();
  @Output() newTypeTwoEvent = new EventEmitter<string>();
  none = "none";
  @Input() selectCount = "";

  sendTypeOne(value: string) {
    this.newTypeOneEvent.emit(value);
  }

  sendTypeTwo(value: string) {
    this.newTypeTwoEvent.emit(value);
  }

}

<div class ="center">
    <div class="typeOneContainer">
        <label for="typeOneSelect">First Type: </label>
        <div class="select">
            <select #typeOne id="typeOneSelect" title="Select a type" (change)="sendTypeOne(typeOne.value)">
                <option [value]="none" [defaultSelected]="true">None</option>
                <option *ngFor="let type of typeList" [value]="type">{{type | titlecase}}</option>
            </select>
            <span class="focus"></span>
        </div>
    </div>
    
    <div *ngIf="selectCount === '2'">
        <div class="typeTwoContainer">
            <label for="typeTwoSelect">Second Type: </label>
            <div class="select">
                <select #typeTwo id="typeTwoSelect" title="Select a type" (change)="sendTypeTwo(typeTwo.value)">
                    <option [value]="none" [defaultSelected]="true">None</option>
                    <option *ngFor="let type of typeList" [value]="type">{{type | titlecase}}</option>
                </select>
                <span class="focus"></span>
            </div>
        </div>
    </div>
</div>
